spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsunggary/notes-manager-config
server:
  port: 9902
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
  client:
    service-url:
      defaultZone: http://106.13.230.143:9901/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
